os:
  - linux

git:
  depth: 1

language: d
d:
  - dmd
  - ldc

  - dmd-2.092.1
  - dmd-2.091.1

  - ldc-1.22.0
  - ldc-1.21.0

script:
  - bash example/test.sh
  - dub test --compiler=${DC} --build=unittest-cov

after_success:
  - if [[ ${DC} == "dmd" ]]; then bash <(curl -s https://codecov.io/bash); fi
