os:
  - linux

git:
  depth: 1

language: d
d:
  - dmd
  - ldc

  - dmd-2.092.1
  - dmd-2.091.1
  - dmd-2.090.1

  - ldc-1.22.0
  - ldc-1.21.0
  - ldc-1.20.1

script:
  - dub test --compiler=${DC} --build=unittest-cov
  - sh example/test.sh

after_success:
  - if [[ ${DC} == "dmd" ]]; then bash <(curl -s https://codecov.io/bash); fi