os:
  - linux

git:
  depth: 1

language: d
d:
  - dmd
  - ldc

  - dmd-2.093.1
  - dmd-2.092.1
  - dmd-2.091.1
  - dmd-2.090.1

  - ldc-1.23.0
  - ldc-1.22.0
  - ldc-1.21.0
  - ldc-1.20.0

script:
  - dub test --compiler=${DC} --build=unittest-cov
  - bash example/test.sh

after_success:
  - if [[ $(cut -d'.' -f2 <<< $TRAVIS_JOB_NUMBER) == "1" ]]; then bash <(curl -s https://codecov.io/bash); fi
