name: Run all D Tests
on: [pull_request]

jobs:
    test:
        name: Dub Tests
        strategy:
            matrix:
                os: [ubuntu-latest]
                dc: [dmd-latest, ldc-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2

            - name: Install D compiler
              uses: dlang-community/setup-dlang@v1
              with:
                  compiler: ${{ matrix.dc }}

            - name: Run tests
              run: |
                dub -q test
                dub --single example/bcoop.d
                dub --single example/struct.d
                #dub --single example/cache.d
                dub --single example/range.d
                dub --single example/wrapobj.d
